name: Daily Commit

on:
  schedule:
    - cron: '30 7 * * *' # Runs every day at 07:30 UTC
  workflow_dispatch:      # Enables manual run for testing

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make Dummy Change
        run: |
          echo "// daily commit $(date)" >> daily.txt

      - name: Commit and Push Changes - 23f2003651@ds.study.iitm.ac.in
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "23f2003651@ds.study.iitm.ac.in"
          git add daily.txt
          git commit -m "Daily commit: $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
