name: Daily Commit

on:
  schedule:
    - cron: '17 5 * * *'  # daily at 05:17 UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make a dummy change (23f2003651@ds.study.iitm.ac.in)
        run: echo "Daily ping: $(date -u)" >> daily-log.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit: $(date -u)" || echo "No changes to commit"
          git push
